### ISSUE TITLE
issue with 2.5.1_308

### ISSUE THREAD

**Issue by adamenger** [boxen/puppet-alfred#30]
Receiving this error when running Boxen:

```
Error: Execution of '/usr/bin/ditto -xk /opt/boxen/cache/Alfred 2.app.zip /Applications' returned 1: ditto: Couldn't read PKZip signature
```

Turns out the package it's looking for doesn't exist anymore.  Can we update this to Alfred_2.7.1_387.zip ? I'll submit a PR soon.

```
$> curl -I https://cachefly.alfredapp.com/Alfred_2.5.1_308.zip
HTTP/1.1 404 Not Found
Date: Fri, 17 Apr 2015 21:40:55 GMT
Content-Type: application/zip
Content-Length: 571
Connection: keep-alive
Server: CFS 0213
X-CF1: 14897:fH.ord1:nom:cacheA.ord1-01:P
```

**Comment by adamenger** [comment]
OK. PR is [here](https://github.com/boxen/puppet-alfred/pull/31).

Cheers

**Comment by eshaham** [comment]
I'm experiencing the same, PR seems to solve the problem.
Please merge.

**Comment by lucasmazza** [comment]
Version `1.5.0` downloads Alfred 2.7.1 now.
